### ISSUE TITLE
Stop auto deployment

### ISSUE THREAD

**Issue by Thykof** [massalabs/massa-sc-playground#47]
The current Github Action workflow deploy the playground at each merge into main branch.

We need to change this: deploy on each release.

**Comment by peterjah** [comment]
I think the easiest way is to trigger a workflow when a version tag is pushed on main. just like this for a tag vX.Y.Z pushed on main:
```
on:
  push:
    branches:    
      - main
    tag
      - v*
 ```
